name: Tests
on: [push, pull_request]

jobs:
  unit_tests:
    name: Index html update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Run code update
        uses: ./containers/run_php_update
      - name: Commit updated index.html
        uses: stefanzweifel/git-auto-commit-action@v4.1.6
        with:
          commit_message: Apply index.html update
          branch: ${{ github.head_ref }}

          # todo - use author name of triggering commit.
          # author_name: Your Name

            # Optional commit user and author settings
            # commit_user_name: My GitHub Actions Bot
            # commit_user_email: my-github-actions-bot@example.org
          # commit_author: Author <actions@github.com>